### ISSUE TITLE
User Stories Completed Issue (3/23/16)

### ISSUE THREAD

**Issue by Blistin** [wildmustard/Gaia-iOS#14]
Completed our basic user stories and application is working! :fire:

**Comment by Aclark2089** [comment]
![gaia-submission-3-tagging](https://cloud.githubusercontent.com/assets/6467543/14035604/a9658f22-f206-11e5-85f3-d0f7b68cb5ef.gif)

We are in business

**Comment by Aclark2089** [comment]
![gaia-submission-3](https://cloud.githubusercontent.com/assets/6467543/14035616/c49bba32-f206-11e5-980f-529f8902a6d4.gif)

Submission GIF

**Comment by Blistin** [comment]
Check out our awesome gifs on the README.

Ready for review /cc @codepathreview

**Comment by minhkhang1795** [comment]
:tada: Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app.
