### ISSUE TITLE
Database Models Submission (2/25/16)

### ISSUE THREAD

**Issue by Blistin** [wildmustard/Gaia-iOS#3]
Added Database Models and other updates to README, ready for review! /cc @codepathreview

**Comment by minhkhang1795** [comment]
:+1: Nice work on getting the data schema defined! Next week we jump into the first implementation sprint. You'll have 3 sprints (one week each) to complete all the required stories for your app and 2 sprints (one week each) to work on optionals and add polish. Let us know if we can help in any way!
