### ISSUE TITLE
66% User Story Completion

### ISSUE THREAD

**Issue by Blistin** [wildmustard/Gaia-iOS#9]
## Additions for this week
- Home now has ability to capture images, save/cancel options, and send those images to the parse server. Mask banner for tags added and custom button implemented
- Image collection view setup and importing images from the parse server that we have taken. Images correctly imported. Has refresh control feature to import newly taken images.

**Comment by johnhenning** [comment]
I'm still working on the backend neural network server. Have Rest Endpoints setup with flask server. Now retraining network with better data.

**Comment by Aclark2089** [comment]
<img src='http://i.imgur.com/ZLAekpN.gifv' title='Submission 2 Gif' width='' alt ='Submission 2 Gif' />

**Comment by Aclark2089** [comment]
![Link to this weeks GIF (was too large)](http://imgur.com/ZLAekpN)

**Comment by Blistin** [comment]
[Submission Gif (was too large)](http://i.imgur.com/ZLAekpN.gifv)

**Comment by Blistin** [comment]
Ready for review!! /cc @codepathreview

**Comment by minhkhang1795** [comment]
:+1: Nice work on the second implementation sprint! Your required user stories are almost completed. There's one week left to complete all of the required stories, add some extra optional functionalities and polish UI design. 
Excited to see your progress next week!
